### PR TITLE
Add BitbucketCloud support

### PR DESCRIPTION
**Pull request by vchernyshov**
This PR add support of BitBucketCloud support

### CODE REVIEW

**Review by gianluz — APPROVED** [review]
Looking great thank you very much for your PR!

**Comment by gianluz** [comment]
Mind just add an entry to the CHANGELOG? Thank you very much!

**Comment by vchernyshov** [comment]
@gianluz done)

**Review by f-meloni — APPROVED** [review]

**Comment by f-meloni** [comment]
Merged! :)

**Comment by vchernyshov** [comment]
@f-meloni cool) Can I get snapshot or beta version with BitBucket cloud support?

**Comment by f-meloni** [comment]
@vchernyshov let me draft a release for it :)

**Comment by f-meloni** [comment]
@vchernyshov 1.1.0 should be released now :)

**Comment by f-meloni** [comment]
> @f-meloni thanks a lot!) one more question: how I can use models from danger-kotlin-library in my own plugin?

I think the simplest way is to pass the values to the function you use to invoke your plugin.

So if you have something like

```kotlin
package com.test.myawesomeplugin

import systems.danger.kotlin.sdk.DangerPlugin

object MyAwesomeDangerPlugin : DangerPlugin() {
    override val id: String
            get() = this.javaClass.name
    
    fun helloPlugin() {
        ...
    }
}
```

you can make helloPlugin take the values you need, for example the base branch name, and then pass it when you invoke it from Danger

```kotlin
  register plugin MyAwesomePlugin

  val danger = Danger(args)

  MyAwesomePlugin.helloPlugin(danger.github...)
```

**Pull request merged**
