### PR TITLE
danger-kotlin cannot compile on Xcode 15+

### PR DESCRIPTION
**Pull request by mrbass21**
danger-kotlin will not compile on native mac using Xcode 15+. This seems to be due to Kotlin. Kotlin seems to have resolved this in version [1.9.10](https://youtrack.jetbrains.com/issue/KT-60230).

I don't know Kotlin tooling that well, so please let me know if I've missed anything in this PR that needs to be addressed. I was able to run the gradlew commands in the make file and all of them build successfully.

Thanks!

### CODE REVIEW

**Comment by Vacxe** [comment]
@mrbass21 Hey mate, thanks for the contribution!

However,  that does not make sense to upgrade kotlin to that version because the latest is higher (check on kotlin website), I'll be happy to merge this PR if you can update it.

**Comment by mrbass21** [comment]
Just letting you know I'm working on this. I'm not an Android or Kotlin developer and the builds break when Kotlin is updated. I'm seeing if I can fix them.

**Comment by snowe2010** [comment]
@mrbass21 I think you're a Kotlin dev now. You got through a major Gradle and JVM upgrade in one PR. 😄

**Comment by mrbass21** [comment]
> @mrbass21 I think you're a Kotlin dev now. You got through a major Gradle and JVM upgrade in one PR. 😄

Not qualified yet! This one only has a Kotlin bump. We'll have to delay the celebration :stuck_out_tongue_closed_eyes:

**Comment by Vacxe** [comment]
Gradle and Kotlin versions has been updated #251 with pipeline fixing. Could you please check with the latest master branch please?

**Comment by mrbass21** [comment]
> Gradle and Kotlin versions has been updated #251 with pipeline fixing. Could you please check with the latest master branch please?

Was able to build from main with Xcode 16 and macOS 15.0.1.

**Pull request closed without merging**
