### PR TITLE
Example Utils internal and as an object

### PR DESCRIPTION
**Pull request by gianluz**

### CODE REVIEW

**Comment by davidbilik** [comment]
Hi @gianluz 👋  have you seen my PR #105 where I try to solve the exact same issue as you did here? :\

**Comment by davidbilik** [comment]
> Hi @gianluz 👋 have you seen my PR #105 where I try to solve the exact same issue as you did here? :\

Oh I see the comments now :) ok then

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Any Changes To Library Code Should Be Reflected In The Changelog.

Please Consider Adding A Note There And Adhere To The [Changelog Guidelines](https://github.com/Moya/contributors/blob/master/Changelog%20Guidelines.md).
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems">Danger Kotlin</a> against 373cb2cd496cd245870b23763b6d2f77e74adfdf
</p>

**Comment by gianluz** [comment]
Yep, just an example to show my idea, but let @f-meloni to have a look as well

**Pull request closed without merging**
