### PR TITLE
Danger kotlin library 0.1.0

### PR DESCRIPTION
**Pull request by gianluz**
Updated danger kotlin library and relative `DangerKotlin.kts` script pointing to the new version

### CODE REVIEW

**Comment by f-meloni** [comment]
`0.1.0`? :)
Is early for the 1.0.0

**Comment by f-meloni** [comment]
We will go with 1.0.0 when we finish the roadmap, then in the meantime if we manage to solve how to release we can release and have a CHANGELOG

**Comment by gianluz** [comment]
fair enough

**Comment by f-meloni** [comment]
Great!
merge on green

**Pull request merged**
