### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by f-meloni**

### CODE REVIEW

**Comment by orta** [comment]
Theres a lot of generated files in here, that on purpose?

**Comment by f-meloni** [comment]
I think they are from @gianluz's commit, then he is the best person to answer to that (i'm not sure :O)

**Comment by f-meloni** [comment]
this is still WIP anyway because 
https://github.com/holgerbrandl/kscript/issues/197
will make danger fail with gradle 5

**Comment by f-meloni** [comment]
Good news is that it works on linux, bad news it doesn't work on macos because of the bug i linked there

**Comment by gianluz** [comment]
Removed generated and ignored files not yet removed from the repo :) i just forgot to remove manually after i updated the .gitignore

**Comment by f-meloni** [comment]
Given the problem with gradle 5 is not related to this PR i will merge this one, hoping that will be solved directly in kscript and that would make it automatically work with gradle 5 too

**Pull request merged**
